"""PDF Credit Profile Report generator using fpdf2."""

import io
from datetime import datetime, timezone
from fpdf import FPDF

# ── Colors (print-friendly professional theme) ───────────────────

NAVY = (15, 23, 42)
DARK_BLUE = (30, 58, 95)
ACCENT = (59, 130, 246)
GREEN = (34, 197, 94)
RED = (220, 38, 38)
GRAY = (100, 116, 139)
LIGHT_BG = (241, 245, 249)
WHITE = (255, 255, 255)


class RAROCReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return  # Cover page has custom header
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*GRAY)
        self.cell(0, 8, "OpenRAROC Credit Profile Report", align="L")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*ACCENT)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*GRAY)
        self.cell(0, 8, "Generated by OpenRAROC (openraroc.com) | Data from public Pillar 3 regulatory filings", align="C")

    def _section_title(self, title):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*NAVY)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*ACCENT)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(4)

    def _table_header(self, widths, labels):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*DARK_BLUE)
        self.set_text_color(*WHITE)
        for w, label in zip(widths, labels):
            self.cell(w, 7, label, border=0, fill=True, align="C")
        self.ln()
        self.set_text_color(*NAVY)

    def _table_row(self, widths, values, aligns=None, bold_first=False, row_idx=0):
        aligns = aligns or ["L"] * len(values)
        self.set_font("Helvetica", "", 8)
        if row_idx % 2 == 0:
            self.set_fill_color(*LIGHT_BG)
        else:
            self.set_fill_color(*WHITE)
        for i, (w, val, align) in enumerate(zip(widths, values, aligns)):
            if bold_first and i == 0:
                self.set_font("Helvetica", "B", 8)
            else:
                self.set_font("Helvetica", "", 8)
            self.cell(w, 6, str(val), border=0, fill=True, align=align)
        self.ln()


def _fmt(v):
    if abs(v) >= 1_000_000:
        return f"{v/1_000_000:,.1f}M"
    if abs(v) >= 1_000:
        return f"{v/1_000:,.0f}K"
    return f"{v:,.0f}"


def generate_report(
    company_name: str,
    facilities: list[dict],
    portfolio_summary: dict,
    comparisons: list[dict],
    optimization: dict | None = None,
    config: dict | None = None,
) -> bytes:
    """Generate a PDF credit profile report.

    Args:
        company_name: Company name for the cover page
        facilities: List of facility dicts with input/output
        portfolio_summary: Portfolio aggregate metrics
        comparisons: Bank comparison results (from compare-portfolio)
        optimization: Optional optimization results
        config: Engine configuration

    Returns:
        PDF file as bytes
    """
    pdf = RAROCReport()
    now = datetime.now(timezone.utc)
    target_raroc = (config or {}).get("target_raroc", 0.12)

    # ── Page 1: Cover ────────────────────────────────────────────

    pdf.add_page()
    pdf.ln(50)

    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 15, "Credit Profile Report", align="C", new_x="LMARGIN", new_y="NEXT")

    if company_name:
        pdf.set_font("Helvetica", "", 20)
        pdf.set_text_color(*ACCENT)
        pdf.cell(0, 12, company_name, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 8, now.strftime("%B %d, %Y"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"{len(facilities)} facilities | {len(comparisons)} banks compared", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(30)
    pdf.set_draw_color(*ACCENT)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(8)

    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 6, "See your credit through your banker's eyes", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, "Generated by OpenRAROC | openraroc.com", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "Bank data from public Pillar 3 CR6 regulatory filings", align="C", new_x="LMARGIN", new_y="NEXT")

    # ── Page 2: Executive Summary ────────────────────────────────

    pdf.add_page()
    pdf._section_title("Executive Summary")

    ps = portfolio_summary
    p_raroc = ps.get("portfolio_raroc", 0)
    best = comparisons[0] if comparisons else {}
    worst = comparisons[-1] if comparisons else {}

    # Key metrics grid
    metrics = [
        ("Portfolio RAROC", f"{p_raroc*100:.2f}%"),
        ("Total Exposure", _fmt(ps.get("total_exposure", 0))),
        ("Economic Capital (FPE)", _fmt(ps.get("total_fpe", 0))),
        ("Total Revenue", _fmt(ps.get("total_revenue", 0))),
        ("Expected Loss", _fmt(ps.get("total_expected_loss", 0))),
        ("Facilities", str(ps.get("count", len(facilities)))),
    ]

    pdf.set_font("Helvetica", "", 9)
    col_w = 62
    for i, (label, value) in enumerate(metrics):
        x = 10 + (i % 3) * col_w
        y = pdf.get_y()
        if i % 3 == 0 and i > 0:
            pdf.ln(18)
            y = pdf.get_y()

        pdf.set_xy(x, y)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GRAY)
        pdf.cell(col_w, 5, label)
        pdf.set_xy(x, y + 5)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*NAVY)
        pdf.cell(col_w, 8, value)

    pdf.ln(24)

    # Key insight
    if best and worst:
        spread_diff = abs(best.get("raroc", 0) - worst.get("raroc", 0)) * 100
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*NAVY)
        pdf.multi_cell(0, 6,
            f"Best bank: {best.get('bank_name', 'N/A')} ({best.get('raroc', 0)*100:.2f}% RAROC). "
            f"Worst bank: {worst.get('bank_name', 'N/A')} ({worst.get('raroc', 0)*100:.2f}% RAROC). "
            f"The {spread_diff:.0f} percentage point spread reflects differences in cost structure, "
            f"tax rates, and funding costs across banks."
        )

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(0, 5,
        f"Target RAROC: {target_raroc*100:.0f}%. Banks above this threshold find your portfolio profitable; "
        f"banks below may require higher spreads or more collateral."
    )

    # ── Page 3: Bank Comparison ──────────────────────────────────

    pdf.add_page()
    pdf._section_title("Bank Comparison")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 6, f"Portfolio RAROC across {len(comparisons)} banks (ranked best to worst):", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Bar chart (simple horizontal bars)
    if comparisons:
        max_raroc = max(c.get("raroc", 0) for c in comparisons)
        min_raroc = min(c.get("raroc", 0) for c in comparisons)
        bar_max = max(abs(max_raroc), abs(min_raroc), 0.01)

        for i, c in enumerate(comparisons[:20]):  # top 20
            y = pdf.get_y()
            if y > 260:
                pdf.add_page()
                pdf._section_title("Bank Comparison (continued)")
                y = pdf.get_y()

            raroc = c.get("raroc", 0)
            bar_w = max(abs(raroc) / bar_max * 90, 1)
            color = GREEN if raroc >= target_raroc else RED

            pdf.set_xy(10, y)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*NAVY)
            pdf.cell(40, 5, c.get("bank_name", "")[:22], align="R")

            pdf.set_xy(52, y)
            pdf.set_fill_color(*color)
            pdf.cell(bar_w, 5, "", fill=True)

            pdf.set_xy(145, y)
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(*color)
            pdf.cell(20, 5, f"{raroc*100:.2f}%", align="R")

            pdf.set_text_color(*GRAY)
            pdf.set_font("Helvetica", "", 7)
            pdf.cell(25, 5, f"  {c.get('country', '')}", align="L")

            pdf.ln(6)

    # Comparison table
    pdf.ln(4)
    widths = [40, 25, 18, 18, 25, 25, 20, 20]
    labels = ["Bank", "Country", "C/I", "Tax", "Exposure", "FPE", "Exp. Loss", "RAROC"]
    pdf._table_header(widths, labels)

    for i, c in enumerate(comparisons[:25]):
        raroc = c.get("raroc", 0)
        vals = [
            c.get("bank_name", "")[:22],
            c.get("country", ""),
            f"{c.get('cost_to_income', 0)*100:.0f}%",
            f"{c.get('tax_rate', 0)*100:.0f}%",
            _fmt(c.get("total_exposure", 0)),
            _fmt(c.get("total_fpe", 0)),
            _fmt(c.get("total_el", 0)),
            f"{raroc*100:.2f}%",
        ]
        aligns = ["L", "L", "C", "C", "R", "R", "R", "R"]

        if pdf.get_y() > 265:
            pdf.add_page()
            pdf._table_header(widths, labels)

        pdf._table_row(widths, vals, aligns, bold_first=True, row_idx=i)

    # ── Per-Facility Breakdown ───────────────────────────────────

    pdf.add_page()
    pdf._section_title("Per-Facility Breakdown")

    f_widths = [35, 25, 15, 15, 25, 20, 20, 20, 18]
    f_labels = ["Facility", "Product", "Rating", "Maturity", "Exposure", "Spread", "Revenue", "Exp. Loss", "RAROC"]
    pdf._table_header(f_widths, f_labels)

    for i, fac in enumerate(facilities):
        inp = fac.get("input", {})
        out = fac.get("output", {})
        name = fac.get("name", f"Facility {i+1}")

        vals = [
            name[:20],
            inp.get("product_type", "")[:14],
            inp.get("rating", ""),
            f"{inp.get('residual_maturity', 0):.0f}m",
            _fmt(out.get("exposure", 0)),
            f"{inp.get('spread', 0)*10000:.0f}bp",
            _fmt(out.get("revenue", 0)),
            _fmt(out.get("average_loss", 0)),
            f"{out.get('raroc', 0)*100:.2f}%",
        ]
        aligns = ["L", "L", "C", "C", "R", "R", "R", "R", "R"]

        if pdf.get_y() > 265:
            pdf.add_page()
            pdf._table_header(f_widths, f_labels)

        pdf._table_row(f_widths, vals, aligns, bold_first=True, row_idx=i)

    # ── Optimization Recommendation ──────────────────────────────

    if optimization and optimization.get("status") == "optimal":
        pdf.add_page()
        pdf._section_title("Optimization Recommendation")

        opt = optimization
        summary = opt.get("summary", {})

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*NAVY)
        saving = summary.get("saving", 0)
        saving_pct = summary.get("saving_pct", 0)
        if saving >= 0:
            pdf.multi_cell(0, 6,
                f"By reallocating facilities optimally across {summary.get('banks_used', 0)} banks, "
                f"total minimum spread cost reduces by {_fmt(abs(saving))} EUR ({abs(saving_pct):.1f}%)."
            )
        else:
            pdf.multi_cell(0, 6,
                f"Current spreads are already {abs(saving_pct):.1f}% below the banks' minimum pricing. "
                f"The optimal allocation across {summary.get('banks_used', 0)} banks shows the most "
                f"cost-efficient arrangement."
            )

        pdf.ln(4)

        # Assignment table
        a_widths = [35, 35, 25, 25, 25, 25, 22]
        a_labels = ["Facility", "Recommended Bank", "Country", "Min Spread", "Current", "Delta", "Status"]
        pdf._table_header(a_widths, a_labels)

        for i, a in enumerate(opt.get("assignments", [])):
            delta = a.get("saving_bp", 0)
            delta_str = f"{'-' if delta >= 0 else '+'}{abs(delta):.0f}bp"
            vals = [
                a.get("facility", "")[:20],
                a.get("bank_name", "")[:20],
                a.get("country", ""),
                f"{a.get('min_spread_bp', 0):.0f}bp",
                f"{a.get('current_spread_bp', 0):.0f}bp",
                delta_str,
                "LOCKED" if a.get("locked") else "",
            ]
            aligns = ["L", "L", "L", "R", "R", "R", "C"]

            if pdf.get_y() > 265:
                pdf.add_page()
                pdf._table_header(a_widths, a_labels)

            pdf._table_row(a_widths, vals, aligns, bold_first=True, row_idx=i)

        pdf.ln(6)

        # Bank allocation summary
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*NAVY)
        pdf.cell(0, 8, "Bank Allocation:", new_x="LMARGIN", new_y="NEXT")

        ba_widths = [45, 35, 30, 20, 20]
        ba_labels = ["Bank", "Region", "Exposure", "Share", "Facilities"]
        pdf._table_header(ba_widths, ba_labels)

        for i, ba in enumerate(summary.get("bank_allocations", [])):
            vals = [
                ba.get("bank_name", ""),
                ba.get("region", ""),
                _fmt(ba.get("exposure", 0)),
                f"{ba.get('pct', 0):.1f}%",
                str(ba.get("facilities", 0)),
            ]
            pdf._table_row(ba_widths, vals, ["L", "L", "R", "R", "C"], bold_first=True, row_idx=i)

    # ── Output ───────────────────────────────────────────────────

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()
